heroes_dict = {
    'Abaddon': 'abaddon',
    'Alchemist': 'alchemist',
    'Anti-Mage': 'antimage',
    'Ancient Apparition': 'ancient_apparition',
    'Arc Warden': 'arc_warden',
    'Axe': 'axe',
    'Bane': 'bane',
    'Batrider': 'batrider',
    'Beastmaster': 'beastmaster',
    'Bloodseeker': 'bloodseeker',
    'Bounty Hunter': 'bounty_hunter',
    'Brewmaster': 'brewmaster',
    'Bristleback': 'bristleback',
    'Broodmother': 'broodmother',
    'Centaur Warrunner': 'centaur',
    'Chaos Knight': 'chaos_knight',
    'Chen': 'chen',
    'Clinkz': 'clinkz',
    'Clockwerk': 'rattletrap',
    'Crystal Maiden': 'crystal_maiden',
    'Dark Seer': 'dark_seer',
    'Dark Willow': 'dark_willow',
    'Dazzle': 'dazzle',
    'Death Prophet': 'death_prophet',
    'Disruptor': 'disruptor',
    'Doom': 'doom_bringer',
    'Dragon Knight': 'dragon_knight',
    'Drow Ranger': 'drow_ranger',
    'Earth Spirit': 'earth_spirit',
    'Earthshaker': 'earthshaker',
    'Elder Titan': 'elder_titan',
    'Ember Spirit': 'ember_spirit',
    'Enchantress': 'enchantress',
    'Enigma': 'enigma',
    'Faceless Void': 'faceless_void',
    'Grimstroke': 'grimstroke',
    'Gyrocopter': 'gyrocopter',
    'Huskar': 'huskar',
    'Invoker': 'invoker',
    'Io': 'wisp',
    'Jakiro': 'jakiro',
    'Juggernaut': 'juggernaut',
    'Keeper of the Light': 'keeper_of_the_light',
    'Kunkka': 'kunkka',
    'Legion Commander': 'legion_commander',
    'Leshrac': 'leshrac',
    'Lich': 'lich',
    'Lifestealer': 'life_stealer',
    'Lina': 'lina',
    'Lion': 'lion',
    'Lone Druid': 'lone_druid',
    'Luna': 'luna',
    'Lycan': 'lycan',
    'Marci': 'marci',
    'Magnus': 'magnataur',
    'Medusa': 'medusa',
    'Meepo': 'meepo',
    'Mirana': 'mirana',
    'Morphling': 'morphling',
    'Monkey King': 'monkey_king',
    'Naga Siren': 'naga_siren',
    "Nature's Prophet": 'furion',
    'Necrophos': 'necrolyte',
    'Night Stalker': 'night_stalker',
    'Nyx Assassin': 'nyx_assassin',
    'Ogre Magi': 'ogre_magi',
    'Omniknight': 'omniknight',
    'Oracle': 'oracle',
    'Outworld Destroyer': 'obsidian_destroyer',
    'Pangolier': 'pangolier',
    'Phantom Assassin': 'phantom_assassin',
    'Phantom Lancer': 'phantom_lancer',
    'Phoenix': 'phoenix',
    'Puck': 'puck',
    'Pudge': 'pudge',
    'Pugna': 'pugna',
    'Queen of Pain': 'queenofpain',
    'Razor': 'razor',
    'Riki': 'riki',
    'Rubick': 'rubick',
    'Sand King': 'sand_king',
    'Shadow Demon': 'shadow_demon',
    'Shadow Fiend': 'nevermore',
    'Shadow Shaman': 'shadow_shaman',
    'Silencer': 'silencer',
    'Skywrath Mage': 'skywrath_mage',
    'Slardar': 'slardar',
    'Slark': 'slark',
    'Snapfire': 'snapfire',
    'Sniper': 'sniper',
    'Spectre': 'spectre',
    'Spirit Breaker': 'spirit_breaker',
    'Storm Spirit': 'storm_spirit',
    'Sven': 'sven',
    'Techies': 'techies',
    'Templar Assassin': 'templar_assassin',
    'Terrorblade': 'terrorblade',
    'Tidehunter': 'tidehunter',
    'Timbersaw': 'shredder',
    'Tinker': 'tinker',
    'Tiny': 'tiny',
    'Treant Protector': 'treant',
    'Troll Warlord': 'troll_warlord',
    'Tusk': 'tusk',
    'Underlord': 'abyssal_underlord',
    'Undying': 'undying',
    'Ursa': 'ursa',
    'Vengeful Spirit': 'vengefulspirit',
    'Venomancer': 'venomancer',
    'Viper': 'viper',
    'Visage': 'visage',
    'Warlock': 'warlock',
    'Weaver': 'weaver',
    'Windranger': 'windrunner',
    'Winter Wyvern': 'winter_wyvern',
    'Witch Doctor': 'witch_doctor',
    'Wraith King': 'skeleton_king',
    'Zeus': 'zuus'
}
